package eventmanager;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author brian
 */
public class createEventUI extends javax.swing.JFrame {

    private final ArrayList<String> inviteList;
  
    /**
     * Creates new form createEventUI
     */
    public createEventUI() {
        initComponents();
        inviteList = new ArrayList<String>();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
       private void retrive()
    {
         DefaultTableModel model = new MySqlConnect().getData();
         ciTable.setModel(model);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        ciCreator = new javax.swing.JTextField();
        ciEventName = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ciDesc = new javax.swing.JTextArea();
        ciMonth = new javax.swing.JComboBox();
        ciDay = new javax.swing.JComboBox();
        ciYear = new javax.swing.JComboBox();
        ciTime = new javax.swing.JComboBox();
        ciWhere = new javax.swing.JComboBox();
        ciWeatherButton = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ciGuest = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        invites = new javax.swing.JLabel();
        ciButton = new javax.swing.JLabel();
        ciAddButton = new javax.swing.JLabel();
        viewButton = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ciTable = new javax.swing.JTable();
        ciUpdateButton = new javax.swing.JLabel();
        ciDeleteUpdate = new javax.swing.JLabel();
        logoutButton = new javax.swing.JLabel();
        ciMin = new javax.swing.JComboBox();
        ciToD = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        createBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ciCreator.setBorder(null);
        ciCreator.setOpaque(false);
        ciCreator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciCreatorActionPerformed(evt);
            }
        });
        jPanel1.add(ciCreator, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 86, 250, -1));

        ciEventName.setBorder(null);
        ciEventName.setOpaque(false);
        jPanel1.add(ciEventName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 127, 250, -1));

        ciDesc.setColumns(20);
        ciDesc.setRows(5);
        ciDesc.setBorder(null);
        ciDesc.setOpaque(false);
        jScrollPane2.setViewportView(ciDesc);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 550, 110));

        ciMonth.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ciMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jPanel1.add(ciMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 50, -1));

        ciDay.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ciDay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(ciDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 50, -1));

        ciYear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ciYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2017", "2018" }));
        jPanel1.add(ciYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, -1, -1));

        ciTime.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ciTime.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jPanel1.add(ciTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, -1, -1));

        ciWhere.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ciWhere.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cal State Channel Islands", "UC Santa Barbara", "Cal State Northridge" }));
        jPanel1.add(ciWhere, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 200, -1));

        ciWeatherButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eventmanager/weather.png"))); // NOI18N
        ciWeatherButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ciWeatherButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ciWeatherButtonMouseClicked(evt);
            }
        });
        jPanel1.add(ciWeatherButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 90, 50));

        ciGuest.setColumns(20);
        ciGuest.setRows(5);
        ciGuest.setBorder(null);
        ciGuest.setOpaque(false);
        jScrollPane3.setViewportView(ciGuest);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 476, 360, 90));

        jScrollPane4.setViewportView(invites);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 480, 200, 150));

        ciButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eventmanager/invite.png"))); // NOI18N
        ciButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ciButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ciButtonMouseClicked(evt);
            }
        });
        jPanel1.add(ciButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 510, -1, 40));

        ciAddButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eventmanager/add.png"))); // NOI18N
        ciAddButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ciAddButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ciAddButtonMouseClicked(evt);
            }
        });
        jPanel1.add(ciAddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, 80, 50));

        viewButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eventmanager/view.png"))); // NOI18N
        viewButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewButtonMouseClicked(evt);
            }
        });
        jPanel1.add(viewButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 590, 90, 70));

        ciTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        ciTable.setOpaque(false);
        ciTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ciTableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(ciTable);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 700, 670, 120));

        ciUpdateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eventmanager/update.png"))); // NOI18N
        ciUpdateButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ciUpdateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ciUpdateButtonMouseClicked(evt);
            }
        });
        jPanel1.add(ciUpdateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 840, 90, 50));

        ciDeleteUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eventmanager/delete.png"))); // NOI18N
        ciDeleteUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ciDeleteUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ciDeleteUpdateMouseClicked(evt);
            }
        });
        jPanel1.add(ciDeleteUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 850, 90, 40));

        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eventmanager/logout.png"))); // NOI18N
        logoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutButtonMouseClicked(evt);
            }
        });
        jPanel1.add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 850, 90, 40));

        ciMin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ciMin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        jPanel1.add(ciMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, -1, -1));

        ciToD.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ciToD.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A.M.", "P.M." }));
        jPanel1.add(ciToD, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, -1, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText(":");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 330, 10, -1));

        createBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eventmanager/createEventsUI.PNG"))); // NOI18N
        jPanel1.add(createBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 930));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 930, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ciCreatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciCreatorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ciCreatorActionPerformed

    private void ciAddButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ciAddButtonMouseClicked
        // TODO add your handling code here:
        
            if (new MySqlConnect().add(ciCreator.getText(),ciEventName.getText(), ciDesc.getText(), 
                    ciMonth.getSelectedItem().toString(), ciDay.getSelectedItem().toString(), ciYear.getSelectedItem().toString(), 
                    ciWhere.getSelectedItem().toString()))
            {
                ciCreator.setText(null);
                ciEventName.setText(null);
                ciDesc.setText(null);
                ciMonth.setSelectedItem(00);
                ciDay.setSelectedItem(00);
                ciYear.setSelectedItem(0000);
                ciWhere.setSelectedItem(0);
                retrive();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "data not added");
            }
    }//GEN-LAST:event_ciAddButtonMouseClicked

    private void viewButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewButtonMouseClicked
        // TODO add your handling code here:
           retrive();
    }//GEN-LAST:event_viewButtonMouseClicked

    private void ciUpdateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ciUpdateButtonMouseClicked
        // TODO add your handling code here:
        int index = ciTable.getSelectedRow();
        String id = ciTable.getValueAt(index, 0).toString();
       
        
       
        if (new MySqlConnect().update(id, ciCreator.getText(), ciEventName.getText(), ciDesc.getText(), 
                                  ciMonth.getSelectedItem().toString(), ciDay.getSelectedItem().toString(), ciYear.getSelectedItem().toString(), 
                                  ciWhere.getSelectedItem().toString()))
            {
             ciCreator.getText();
             ciEventName.setText(null);
             ciDesc.setText(null);
             ciMonth.setSelectedItem(00);
             ciDay.setSelectedItem(00);
             ciYear.setSelectedItem(0000);
             ciWhere.setSelectedItem(0);
             
             retrive();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "data not updated");
            }  
        
    }//GEN-LAST:event_ciUpdateButtonMouseClicked

    private void ciDeleteUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ciDeleteUpdateMouseClicked
        // TODO add your handling code here:
      String[] option = {"yes" , "no"};
      int answer = JOptionPane.showOptionDialog(null, "sure to delete??", "delete confirm", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, option, option[1]);
      
      if (answer == 0)
      {
        int index = ciTable.getSelectedRow();
        String id = ciTable.getValueAt(index, 0).toString();
        
            if (new MySqlConnect().delete(id))
                    //ciEventName.getText(), ciDesc.getText(), 
                      //            ciMonth.getSelectedItem().toString(), ciDay.getSelectedItem().toString(), ciYear.getSelectedItem().toString(), 
                       //           ciWhere.getSelectedItem().toString(), ciCreator.getText()))
            {
                JOptionPane.showMessageDialog(null, "data deleted");
                ciCreator.setText(""); 
                ciEventName.setText("");
                ciDesc.setText("");
                ciMonth.setSelectedItem("");
                ciDay.setSelectedItem("");
                ciYear.setSelectedItem("");
                ciWhere.setSelectedItem(""); 
                retrive();
            }
            else
            {
               JOptionPane.showMessageDialog(null, "data not deleted"); 
            }
      } 
    }//GEN-LAST:event_ciDeleteUpdateMouseClicked

    private void ciTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ciTableMouseClicked
        // TODO add your handling code here:
        String creator = ciTable.getValueAt(ciTable.getSelectedRow(), 1).toString();
        String name = ciTable.getValueAt(ciTable.getSelectedRow(), 2).toString();
        String descr = ciTable.getValueAt(ciTable.getSelectedRow(), 3).toString();
        String date = ciTable.getValueAt(ciTable.getSelectedRow(), 4).toString();
        String loc = ciTable.getValueAt(ciTable.getSelectedRow(), 5).toString();
        
        
        invites.setText("<html>test<br>test<br>test<br>test2<br>test</html>");
        
        ciCreator.setText(creator);
        ciEventName.setText(name);
        ciDesc.setText(descr);
        ciDay.setSelectedItem(date.substring(0,2));
        ciWhere.setSelectedItem(loc);
        
    }//GEN-LAST:event_ciTableMouseClicked

    private void ciButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ciButtonMouseClicked
        // TODO add your handling code here:
        email email = new email(ciGuest.getText(), ciEventName.getText(), 
                  "DATE: " + ciDay.getSelectedItem() + "/" + ciMonth.getSelectedItem() + "/" + ciYear.getSelectedItem() + "\n" +
                  "TIME: " + ciTime.getSelectedItem() + "/" + ciMin.getSelectedItem() + "/" + ciToD.getSelectedItem() + "\n" +
                  "LOCATION: " + ciWhere.getSelectedItem() + "\n" +
                  "DESCRIPTION: " + ciDesc.getText());
          if (new MySqlConnect().addInvite(ciGuest.getText(), ciEventName.getText()))
            {
                inviteList.add(ciGuest.getText());
        
        
        String newString = "<html>";
        for (String s : inviteList) {
            newString += s;
            newString += "<br>";
        }
        newString += "</html>";
        
        invites.setText(newString);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "data not added");
            }
         
    }//GEN-LAST:event_ciButtonMouseClicked

    private void ciWeatherButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ciWeatherButtonMouseClicked
        // TODO add your handling code here:
    
        String loc = ciWhere.getSelectedItem().toString();
        String code = "";
        switch (loc)
        {
            case "Cal State Channel Islands":
            code = "https://weather.com/weather/monthly/l/USCA0160:1:US";
        {
            try {
                java.awt.Desktop.getDesktop().browse(java.net.URI.create(code));
            } catch (IOException ex) {
                Logger.getLogger(createEventUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
                break;
            case "UC Santa Barbara":
                code = "https://weather.com/weather/monthly/l/USCA1017:1:US";
        {
            try {
                java.awt.Desktop.getDesktop().browse(java.net.URI.create(code));
            } catch (IOException ex) {
                Logger.getLogger(createEventUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
                break;
            case "Cal State Northridge":
                code = "https://weather.com/weather/monthly/l/USCA0780:1:US";
        {
            try {
                java.awt.Desktop.getDesktop().browse(java.net.URI.create(code));
            } catch (IOException ex) {
                Logger.getLogger(createEventUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
                break;
        }
    }//GEN-LAST:event_ciWeatherButtonMouseClicked

    private void logoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseClicked
        // TODO add your handling code here:
        dispose();
        eventManagerUI w = new eventManagerUI();
        w.setVisible(true);
    }//GEN-LAST:event_logoutButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createEventUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createEventUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createEventUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createEventUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new createEventUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ciAddButton;
    private javax.swing.JLabel ciButton;
    private javax.swing.JTextField ciCreator;
    private javax.swing.JComboBox ciDay;
    private javax.swing.JLabel ciDeleteUpdate;
    private javax.swing.JTextArea ciDesc;
    private javax.swing.JTextField ciEventName;
    private javax.swing.JTextArea ciGuest;
    private javax.swing.JComboBox ciMin;
    private javax.swing.JComboBox ciMonth;
    private javax.swing.JTable ciTable;
    private javax.swing.JComboBox ciTime;
    private javax.swing.JComboBox ciToD;
    private javax.swing.JLabel ciUpdateButton;
    private javax.swing.JLabel ciWeatherButton;
    private javax.swing.JComboBox ciWhere;
    private javax.swing.JComboBox ciYear;
    private javax.swing.JLabel createBg;
    private javax.swing.JLabel invites;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel logoutButton;
    private javax.swing.JLabel viewButton;
    // End of variables declaration//GEN-END:variables
}
