/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eventmanager;
import javax.swing.*;
import java.sql.*;

/**
 *
 * @author brian
 */
public class eventManagerUI extends javax.swing.JFrame {
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form eventManagerUI
     */
    public eventManagerUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        email = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        newEmail = new javax.swing.JTextField();
        newPassword = new javax.swing.JTextField();
        fName = new javax.swing.JTextField();
        lName = new javax.swing.JTextField();
        loginBtn = new javax.swing.JButton();
        createBtn = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        email.setBorder(null);
        email.setOpaque(false);
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 130, 20));

        password.setBorder(null);
        password.setOpaque(false);
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 104, 130, 20));

        newEmail.setBorder(null);
        newEmail.setOpaque(false);
        getContentPane().add(newEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 130, 20));

        newPassword.setBorder(null);
        newPassword.setOpaque(false);
        getContentPane().add(newPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 130, 20));

        fName.setBorder(null);
        fName.setOpaque(false);
        fName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNameActionPerformed(evt);
            }
        });
        getContentPane().add(fName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 284, 130, 20));

        lName.setBorder(null);
        lName.setOpaque(false);
        lName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lNameActionPerformed(evt);
            }
        });
        getContentPane().add(lName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 130, 20));

        loginBtn.setBackground(new java.awt.Color(47, 155, 197));
        loginBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        loginBtn.setText("Login");
        loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        getContentPane().add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        createBtn.setBackground(new java.awt.Color(47, 155, 197));
        createBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        createBtn.setText("Create");
        createBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });
        getContentPane().add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        background.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 12)); // NOI18N
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eventmanager/EventsUI.PNG"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNameActionPerformed

    private void lNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lNameActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        conn=MySqlConnect.ConnectDB();
        String Sql = "Select * from MEMBER where email=? and password=?";
        try{    
            pst = conn.prepareStatement(Sql);
            pst.setString(1,email.getText());
            pst.setString(2,password.getText());
            rs = pst.executeQuery();
            if (rs.next())
            {
                JOptionPane.showMessageDialog(null,"Welcome user");
                dispose();
                createEventUI w = new createEventUI();
                w.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Invalid username or password", "Access Denied",JOptionPane.ERROR_MESSAGE);
            }
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
        conn=MySqlConnect.ConnectDB();    
        try{

            Statement stmt = conn.createStatement();
            String Query = "INSERT INTO MEMBER (EMAIL, PASSWORD, FIRST_NAME, LAST_NAME) VALUES "
                    + "('"+newEmail.getText()+"' , '"+newPassword.getText()+"', '"+fName.getText()+"', '"+lName.getText()+"')";
            stmt.execute(Query);
            
            newEmail.setText(null);
            newPassword.setText(null);
            fName.setText(null);
            lName.setText(null);
        }
        
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
        
        
         dispose();
         createEventUI w = new createEventUI();
         w.setVisible(true);
    }//GEN-LAST:event_createBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(eventManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(eventManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(eventManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(eventManagerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new eventManagerUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton createBtn;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fName;
    private javax.swing.JTextField lName;
    private javax.swing.JButton loginBtn;
    private javax.swing.JTextField newEmail;
    private javax.swing.JTextField newPassword;
    private javax.swing.JPasswordField password;
    // End of variables declaration//GEN-END:variables
}
